### ISSUE TITLE
Spawn rabbit with egg error

### ISSUE THREAD

**Issue by iTraumatik** [ganymedes01/Et-Futurum#12]
Getting this error and no rabbit spawn when i click ground with spawn egg.....  

[15:58:49] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.inventory.GuiInventory
[15:58:49] [Client thread/INFO] [inventorytweaks]: net.minecraft.inventory.ContainerPlayer
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Constructor.newInstance(Unknown Source)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at ganymedes01.etfuturum.entities.ModEntityList.createEntityByID(ModEntityList.java:72)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at ganymedes01.etfuturum.items.ItemEntityEgg.spawnEntity(ItemEntityEgg.java:124)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at ganymedes01.etfuturum.items.ItemEntityEgg.func_77648_a(ItemEntityEgg.java:70)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: cpw.mods.fml.relauncher.ReflectionHelper$UnableToAccessFieldException: cpw.mods.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: jumpHelper
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.relauncher.ReflectionHelper.setPrivateValue(ReflectionHelper.java:147)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at ganymedes01.etfuturum.entities.EntityRabbit.<init>(EntityRabbit.java:54)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  ... 20 more
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: cpw.mods.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: jumpHelper
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:94)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.relauncher.ReflectionHelper.setPrivateValue(ReflectionHelper.java:143)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  ... 21 more
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NoSuchFieldException: jumpHelper
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.Class.getDeclaredField(Unknown Source)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:85)
[15:59:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  ... 22 more
[15:59:06] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.inventory.GuiInventory
[15:59:06] [Client thread/INFO] [inventorytweaks]: net.minecraft.inventory.ContainerPlayer

**Comment by buttilda** [comment]
Oh...
Damn, that error would only happen outside of a dev environment, that's why I did't notice.
My apologies. I'll fix it straight away.

**Comment by buttilda** [comment]
Build 1.3.1 has been uploaded with the fix.
