### ISSUE TITLE
Cannot spawn Rabbits in SMP (Et-Futurum 1.3.2)

### ISSUE THREAD

**Issue by DarksideBD** [ganymedes01/Et-Futurum#14]
When you attempt to spawn a rabbit via a spawn egg nothing happens in-game but, an error is thown on the server console:-

```
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.reflect.Constructor.newInstance(Unknown Source)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at ganymedes01.etfuturum.entities.ModEntityList.createEntityByID(ModEntityList.java:72)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at ganymedes01.etfuturum.items.ItemEntityEgg.spawnEntity(ItemEntityEgg.java:124)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at ganymedes01.etfuturum.items.ItemEntityEgg.func_77648_a(ItemEntityEgg.java:70)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class ganymedes01.etfuturum.entities.ai.BlockPos
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at ganymedes01.etfuturum.entities.ai.EntityAIMoveToBlock.<init>(EntityAIMoveToBlock.java:21)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at ganymedes01.etfuturum.entities.EntityRabbit$AIRaidFarm.<init>(EntityRabbit.java:463)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at ganymedes01.etfuturum.entities.EntityRabbit.<init>(EntityRabbit.java:62)
[16:40:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     ... 20 more
```

Tried this out on forge server 1.7.10-10.13.4.1492 and kCauldron server 1.7.10-1492.150, both platforms error out. 

In SSP mode (with the same mods installed) rabbits spawn correctly.

**Comment by buttilda** [comment]
Are you on version 1.3.2 of Et Futurum?

**Comment by DarksideBD** [comment]
Yes, as per the title of this post.

**Comment by buttilda** [comment]
Sorry, was reading it on my phone and it didn't show the whole title.
Thanks for the report, I'll look into it when I can.
