### ISSUE TITLE
1.5.0 player model crashes with Smart Moving

### ISSUE THREAD

**Issue by EzerArch** [ganymedes01/Et-Futurum#55]
The new player model conflicts with Smart Moving mod, which also changes the player model.

```
java.lang.ClassCastException: ganymedes01.etfuturum.client.model.ModelPlayer cannot be cast to api.player.model.ModelPlayer
    at net.smart.render.playerapi.SmartRenderRenderPlayerBase.createModel(SmartRenderRenderPlayerBase.java:48)
    at net.smart.render.SmartRenderRender.<init>(SmartRenderRender.java:39)
    at net.smart.render.playerapi.SmartRenderRenderPlayerBase.getRenderRender(SmartRenderRenderPlayerBase.java:41)
    at net.smart.render.playerapi.SmartRenderRenderPlayerBase.renderFirstPersonArm(SmartRenderRenderPlayerBase.java:77)
```

Full report: https://gist.github.com/EzerArch/590cb30f6c84895ad5ad

---

**EDIT: SOLVED!**

Setting `B:"Skin overlays"=false` can avoid the crash.

Smart Moving with its API: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1274224-smart-moving

**Comment by buttilda** [comment]
Same problem with Optifine.
Any mods that override player rendering won't work with Et Futurum's player models
